<?php $_helper = Mage::helper('macopedia_zanox'); ?>
<?php $_store = Mage::app()->getStore(); ?>
<?php $_code = $_helper->getConfigCode('product'); ?>
<?php echo $this->getLayout()->createBlock('core/template')
	->setTemplate('macopedia/zanox/script.phtml')
	->setZanoxCode($_code)
	->tohtml();
?>
<?php $_product = Mage::registry('current_product'); ?>
<?php if ($_product && $_code) : ?>
	<script type="text/javascript">
		var zx_identifier = "<?php echo $_product->getId(); ?>";
		var zx_fn = "<?php echo $_product->getName(); ?>";
		var zx_description = "<?php echo $_product->getShortDescription(); ?>";
		<?php /*var zx_category = "<?php echo $_product->getId(); ?>"; */?>
		<?php /*var zx_brand = "<?php echo $_product->getId(); ?>"; */?>
		var zx_price = "<?php echo $_store->convertPrice($_product->getPrice()); ?>";
		var zx_currency = "<?php echo $_store->getCurrentCurrencyCode(); ?>";
		var zx_url = "<?php echo $_product->getProductUrl(); ?>";
		var zx_photo = "<?php echo $_product->getImageUrl(); ?>";
		var zx_language = "<?php echo $_helper->getLocaleCode(); ?>"
	</script>
<?php endif; ?>