<?php var_dump(Mage::getStoreConfigFlag('macopedia_zanox/zanox_tags/generic_enable')); ?>

<?php if($this->getZanoxCode()) : ?>
	<div class="zx_<?php echo $this->getZanoxCode(); ?> zx_mediaslot">
		<script type="text/javascript">
			window._zx = window._zx || [];
			window._zx.push({"id":"<?php echo $this->getZanoxCode(); ?>"});
			(function(d) {
				var s = d.createElement("script"); s.async = true;
				s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//static.zanox.com/scripts/zanox.js";
				var a = d.getElementsByTagName("script")[0]; a.parentNode.insertBefore(s, a);
			}(document));
		</script>
	</div>
<?php endif; ?>